
/*推荐栏目*/
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('111','menu', '1', '推荐栏目', '高考必备书目', 25, now(),now());
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('112','menu', '2', '推荐栏目', '中考必备书目', 26, now(),now());
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('113','menu', '3', '推荐栏目', '教育部推荐书目', 27, now(),now());

/*推荐年级*/
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('121','level', '1', '推荐年级', '七年级上', 28, now(),now());
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('122','level', '2', '推荐年级', '七年级下', 29, now(),now());
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('123','level', '3', '推荐年级', '八年级上', 30, now(),now());
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('124','level', '4', '推荐年级', '八年级下', 31, now(),now());
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('125','level', '5', '推荐年级', '九年级上', 32, now(),now());
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('126','level', '6', '推荐年级', '九年级下', 33, now(),now());


/*目录等级*/
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('131','level', '1', '目录等级', '一级目录', 34, now(),now());
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('132','level', '2', '目录等级', '二级目录', 35, now(),now());
INSERT INTO base_system_parameter
(REC_ID,PARAMETER_TYPE, PARAMETER_KEY, PARAMETER_NAME, PARAMETER_VALUE, WEIGHT, CREATE_TIME, UPDATE_TIME)
VALUES ('133','level', '3', '目录等级', '三级目录', 36, now(),now());