

ALTER TABLE task ADD COLUMN  cover   VARCHAR(200) DEFAULT NULL COMMENT '封面' AFTER name;
ALTER TABLE task ADD COLUMN  start_time   VARCHAR(200) DEFAULT NULL COMMENT '封面' AFTER cover;
ALTER TABLE task ADD COLUMN  end_time   VARCHAR(200) DEFAULT NULL COMMENT '封面' AFTER start_time;
