

ALTER TABLE member ADD COLUMN  NAME  VARCHAR(100) DEFAULT NULL COMMENT '姓名' AFTER user_id;
ALTER TABLE member ADD COLUMN  mobile  VARCHAR(20) DEFAULT NULL COMMENT '手机' AFTER user_id;
ALTER TABLE member ADD COLUMN  office_status  VARCHAR(100) DEFAULT NULL COMMENT '在职状态' AFTER mobile;
ALTER TABLE member ADD COLUMN  SUBJECT  VARCHAR(30) DEFAULT NULL COMMENT '学科' AFTER office_status;
ALTER TABLE member ADD COLUMN  PHASE  VARCHAR(100) DEFAULT NULL COMMENT '学段' AFTER office_status;
ALTER TABLE member ADD COLUMN  ORGANIZATION  VARCHAR(100) DEFAULT NULL COMMENT '学校' AFTER office_status;
ALTER TABLE member ADD COLUMN  ID_CARD  VARCHAR(30) DEFAULT NULL COMMENT '身份证' AFTER ORGANIZATION;
ALTER TABLE member ADD COLUMN  STATUS  VARCHAR(10) DEFAULT NULL COMMENT '状态' AFTER ID_CARD;
ALTER TABLE member ADD COLUMN  import_data  VARCHAR(20) DEFAULT NULL COMMENT '是否为导入数据' AFTER user_id;
